apiVersion: v2
name: secure-cloud-infrastructure-platform
description: Hardened deployment chart for the SCIP control-plane API
type: application
version: 0.1.0
appVersion: "0.1.0"
kubeVersion: ">=1.30.0-0 <1.37.0-0"
home: https://github.com/shamddd/secure-cloud-infrastructure-platform
sources:
  - https://github.com/shamddd/secure-cloud-infrastructure-platform
maintainers:
  - name: Sham Satish Thakare
